### ISSUE TITLE
Reconcile prismarine-yggdrasil with node-yggdrasil?

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/prismarine-yggdrasil#2]
This module (prismarine-yggdrasil) was extracted from [node-minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) https://github.com/PrismarineJS/node-minecraft-protocol/issues/117, however there is also another Yggdrasil authentication module on NPM: [node-yggdrasil](https://github.com/zekesonxx/node-yggdrasil), developed by @zekesonxx

Maybe it'd be worth merging these two modules to reduce code duplication/effort? prismarine-yggdrasil doesn't appear to be published on NPM yet so this would be a good time to sort this out, if we want to avoid having two yggdrasils. (Although, there is no harm in having multiple alternatives.)

Looking at node-yggdrasil, it appears to cover the functionality of prismarine-yggdrasil, but is somewhat more flexible, uses [request](https://github.com/request/request) instead of [superagent](https://github.com/visionmedia/superagent), and has unit tests. Hasn't been modified in 11 months though so I don't know how updated it is (or whether it needs to be).

**Comment by deathcap** [comment]
One immediate problem I noticed with node-yggdrasil: it is currently broken on node 0.12 (`npm test` fails), since its request dependency is [broken on 0.12](https://github.com/request/request/commit/5c46172e5a5d48407a6769d867de6b5afc5060d5) (known issue, they're working on it). prismarine-yggdrasil works with node 0.12, and presumably iojs

**Comment by zekesonxx** [comment]
Aside from a lack of documentation node-yggdrasil is basically finished,
although I think it might be missing a method or two.

**Comment by roblabla** [comment]
@zekesonxx we could help with that :smile: . 

I can confirm prismarine-yggdrasil works on iojs. The broken request dependency should get fixed very soon though, so it's not really an issue. Besides, from what I gather in the issues, it's just the tests failing, so no big deal.

All in all, I'm all for using node-yggdrasil, and I agree that there's no need to create two modules for such a simple task.

**Comment by rom1504** [comment]
This is now done. What's the plan for this repo and the corresponding npm package?
Deleting both would seem like a good idea to me, to avoid confusion.

**Comment by rom1504** [comment]
Ah, I guess it would be better to make sure nobody use this first.

**Comment by roblabla** [comment]
Updating the readme to reflect that it is discontinued in favor of node-yggdrasil would be the way forward. As for the NPM package, it's there to stay. It's working anyway, why bother removing it.

**Comment by rom1504** [comment]
Hmm ok

**Comment by zekesonxx** [comment]
I would agree with this. Keep it up, but make it clear that node-yggdrasil is to be used instead.

**Comment by rom1504** [comment]
this is long done
